services:
  - type: web
    name: ml-project
    env: python
    buildCommand: "pip install -r requirements.txt && python -m nltk.downloader stopwords"
    startCommand: "uvicorn src.web.app:app --host 0.0.0.0 --port $PORT"
